/**
 * Cessna 172S NAV III (G1000 NXi) with the GFC 700 AFCS: POH checklists.
 *
 * Wording from the Cessna 172S NAV III GFC 700 AFCS POH/AFM 172SPHBUS-00 (20 Dec 2007),
 * Section 4 "Normal procedures" (checklist form, pages 4-4 .. 4-22) and Section 3
 * "Emergency procedures" (3-6 .. 3-24), abbreviated only where the POH item is an
 * explanation. This airplane's Before Takeoff list differs from the KAP 140 NAV III and the
 * steam POHs (autopilot engage / override check, A/P TRIM DISC, Flight Director OFF), and
 * the emergency lists add the STBY BATT switch. Items with a `check` show a live tick.
 */
import type { Checklist } from '../types';
import type { SimContext } from '../../core/SimContext';
import { ENG, FDM, SURF } from '../../core/vars';
import { ANN, C172, FUEL_SEL, MAG, STBY_BATT } from '../c172s-common/vars';

type V = SimContext['vars'];
const on = (name: string) => (v: V) => v.get(name) > 0.5;
const off = (name: string) => (v: V) => v.get(name) < 0.5;
const eq = (name: string, x: number) => (v: V) => Math.round(v.get(name)) === x;
const flaps = (lo: number, hi: number) => (v: V) => v.get(SURF.flapsDeg) >= lo - 0.5 && v.get(SURF.flapsDeg) <= hi + 0.5;
const masterOn = (v: V) => v.get(C172.masterBat) > 0.5 && v.get(C172.masterAlt) > 0.5;
const masterOff = (v: V) => v.get(C172.masterBat) < 0.5 && v.get(C172.masterAlt) < 0.5;
const avionicsOn = (v: V) => v.get(C172.avionicsBus1) > 0.5 && v.get(C172.avionicsBus2) > 0.5;
const avionicsOff = (v: V) => v.get(C172.avionicsBus1) < 0.5 && v.get(C172.avionicsBus2) < 0.5;
const mixtureCutoff = (v: V) => v.get(C172.mixture) < 0.05;
const mixtureRich = (v: V) => v.get(C172.mixture) > 0.8 || v.get(FDM.pressAlt) > 3000;
const throttleIdle = (v: V) => v.get(C172.throttle) < 0.03;

const MASTER = 'MASTER Switch (ALT and BAT)';
const AVIONICS = 'AVIONICS Switch (BUS 1 and BUS 2)';
const STBY = 'STBY BATT Switch';

export const C172G_CHECKLISTS: Checklist[] = [
  // ======================================================================= NORMAL (POH Section 4)
  {
    title: 'Preflight Inspection — Cabin',
    phase: 'preflight',
    items: [
      { challenge: 'Pitot Tube Cover', response: 'REMOVE (check for pitot blockage)' },
      { challenge: "Pilot's Operating Handbook", response: 'ACCESSIBLE TO PILOT' },
      { challenge: 'Garmin G1000 Cockpit Reference Guide', response: 'ACCESSIBLE TO PILOT' },
      { challenge: 'Airplane Weight and Balance', response: 'CHECKED' },
      { challenge: 'Parking Brake', response: 'SET', check: on(C172.parkingBrake) },
      { challenge: 'Control Wheel Lock', response: 'REMOVE', check: off(C172.controlLock) },
      { challenge: 'MAGNETOS Switch', response: 'OFF', check: eq(C172.magneto, MAG.off) },
      { challenge: AVIONICS, response: 'OFF', check: avionicsOff },
      { challenge: MASTER, response: 'ON', check: masterOn },
      { challenge: 'Primary Flight Display (PFD)', response: 'CHECK (verify PFD is ON)', check: on('elec.pfd_powered') },
      { challenge: 'FUEL QTY (L and R)', response: 'CHECK' },
      { challenge: 'LOW FUEL L and LOW FUEL R Annunciators', response: 'CHECK (verify annunciators are not shown on PFD)', check: (v) => v.get(ANN.lowFuelL) < 0.5 && v.get(ANN.lowFuelR) < 0.5 },
      { challenge: 'OIL PRESSURE Annunciator', response: 'CHECK (verify annunciator is shown)', check: on(ANN.oilPress) },
      { challenge: 'LOW VACUUM Annunciator', response: 'CHECK (verify annunciator is shown)', check: on(ANN.lowVacuum) },
      { challenge: 'AVIONICS Switch (BUS 1)', response: 'ON' },
      { challenge: 'Forward Avionics Fan', response: 'CHECK (verify fan is heard)', check: on('ac.c172g.fwd_fan') },
      { challenge: 'AVIONICS Switch (BUS 1)', response: 'OFF' },
      { challenge: 'AVIONICS Switch (BUS 2)', response: 'ON' },
      { challenge: 'Aft Avionics Fan', response: 'CHECK (verify fan is heard)', check: on('ac.c172g.aft_fan') },
      { challenge: 'AVIONICS Switch (BUS 2)', response: 'OFF' },
      { challenge: 'PITOT HEAT Switch', response: 'ON (pitot tube warm to the touch within 30 seconds)' },
      { challenge: 'PITOT HEAT Switch', response: 'OFF', check: off(C172.pitotHeat) },
      { challenge: 'LOW VOLTS Annunciator', response: 'CHECK (verify annunciator is shown)', check: on(ANN.lowVolts) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: 'Elevator Trim Control', response: 'TAKEOFF position', check: (v) => Math.abs(v.get(C172.trimPosition) - 0.1) < 0.12 },
      { challenge: 'FUEL SELECTOR Valve', response: 'BOTH', check: eq(C172.fuelSelector, FUEL_SEL.both) },
      { challenge: 'ALT STATIC AIR Valve', response: 'OFF (push full in)', check: off(C172.altStatic) },
      { challenge: 'Fire Extinguisher', response: 'CHECK (verify gage pointer in green arc)', check: (v) => v.get('ac.c172g.ext_psi') >= 125 },
    ],
  },
  {
    title: 'Preflight Inspection — Exterior',
    phase: 'preflight',
    items: [
      { challenge: 'Baggage Compartment Door', response: 'CHECK (lock with key)' },
      { challenge: 'Rudder Gust Lock; Tail Tiedown', response: 'REMOVE; DISCONNECT' },
      { challenge: 'Control Surfaces; Elevator Trim Tab', response: 'CHECK (freedom of movement and security)' },
      { challenge: 'Antennas', response: 'CHECK (security of attachment and general condition)' },
      { challenge: 'Right Wing: Flap, Aileron, Tiedown, Main Wheel Tire', response: 'CHECK / DISCONNECT' },
      { challenge: 'Fuel Tank Sump Quick Drain Valves', response: 'DRAIN (water, sediment, proper fuel grade)' },
      { challenge: 'Fuel Quantity; Filler Cap', response: 'CHECK VISUALLY; SECURE and VENT CLEAR' },
      { challenge: 'Nose: Fuel Strainer Quick Drain Valve', response: 'DRAIN' },
      { challenge: 'Engine Oil Dipstick/Filler Cap', response: 'CHECK (not less than 5 qt; 8 qt for extended flight); SECURE' },
      { challenge: 'Engine Cooling Air Inlets; Propeller and Spinner; Air Filter', response: 'CHECK' },
      { challenge: 'Nosewheel Strut and Tire; Static Source Opening (left side)', response: 'CHECK' },
      { challenge: 'Left Wing Leading Edge: Fuel Tank Vent, Stall Warning Opening', response: 'CHECK (blockage)' },
      { challenge: 'Landing/Taxi Light(s)', response: 'CHECK (condition and cleanliness of cover)' },
      { challenge: 'Left Wing: Tiedown, Fuel, Sump Drains, Main Wheel Tire, Aileron, Flap', response: 'CHECK / DISCONNECT / DRAIN' },
    ],
  },
  {
    title: 'Before Starting Engine',
    phase: 'before start',
    items: [
      { challenge: 'Preflight Inspection', response: 'COMPLETE' },
      { challenge: 'Passenger Briefing', response: 'COMPLETE' },
      { challenge: 'Seats and Seat Belts', response: 'ADJUST and LOCK (verify inertia reel locking)' },
      { challenge: 'Brakes', response: 'TEST and SET', check: on(C172.parkingBrake) },
      { challenge: 'Circuit Breakers', response: 'CHECK IN' },
      { challenge: 'Electrical Equipment', response: 'OFF' },
      { challenge: AVIONICS, response: 'OFF', check: avionicsOff },
      { challenge: 'FUEL SELECTOR Valve', response: 'BOTH', check: eq(C172.fuelSelector, FUEL_SEL.both) },
      { challenge: 'FUEL SHUTOFF Valve', response: 'ON (push full in)', check: on(C172.fuelShutoff) },
    ],
  },
  {
    title: 'Starting Engine (With Battery)',
    phase: 'start',
    items: [
      { challenge: 'Throttle Control', response: 'OPEN 1/4 INCH', check: (v) => v.get(C172.throttle) > 0.02 && v.get(C172.throttle) < 0.2 },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'STBY BATT Switch: TEST', response: 'HOLD 20 s (verify green TEST lamp does not go off)' },
      { challenge: 'STBY BATT Switch: ARM', response: 'SET (verify that PFD comes on)', check: eq(C172.stbyBatt, STBY_BATT.arm) },
      { challenge: 'Engine Indicating System', response: "CHECK PARAMETERS (verify no red X's through ENGINE page indicators)", check: on('elec.nav1_eng_powered') },
      { challenge: 'BUS E Volts', response: 'CHECK (verify 24 VOLTS minimum shown)', check: (v) => v.get(C172.eBusV) >= 24 },
      { challenge: 'M BUS Volts', response: 'CHECK (verify 1.5 VOLTS or less shown)', check: (v) => v.get(C172.mBusV) <= 1.5 },
      { challenge: 'BATT S Amps', response: 'CHECK (verify discharge shown (negative))', check: (v) => v.get(C172.sBattA) < 0 },
      { challenge: 'STBY BATT Annunciator', response: 'CHECK (verify annunciator is shown)', check: on(ANN.stbyBatt) },
      { challenge: 'Propeller Area', response: 'CLEAR' },
      { challenge: MASTER, response: 'ON', check: masterOn },
      { challenge: 'BEACON Light Switch', response: 'ON', check: on(C172.beacon) },
      { challenge: 'FUEL PUMP Switch', response: 'ON (omit if engine warm)' },
      { challenge: 'Mixture Control', response: 'FULL RICH until stable fuel flow (3-5 s), then IDLE CUTOFF' },
      { challenge: 'FUEL PUMP Switch', response: 'OFF', check: off(C172.fuelPump) },
      { challenge: 'MAGNETOS Switch', response: 'START (release when engine starts)' },
      { challenge: 'Mixture Control', response: 'ADVANCE SMOOTHLY TO RICH (when engine starts)', check: (v) => v.get(C172.mixture) > 0.8 },
      { challenge: 'Oil Pressure', response: 'CHECK (green band within 30 to 60 seconds)', check: (v) => v.get(ENG.oilPressPsi(1)) >= 20 },
      { challenge: 'AMPS (M BATT and BATT S)', response: 'CHECK (verify charge shown (positive))', check: (v) => v.get(C172.mBattA) > 0 && v.get(C172.sBattA) >= 0 },
      { challenge: 'LOW VOLTS Annunciator', response: 'CHECK (verify annunciator is not shown)', check: off(ANN.lowVolts) },
      { challenge: 'NAV Light Switch', response: 'ON as required' },
      { challenge: AVIONICS, response: 'ON', check: avionicsOn },
    ],
  },
  {
    title: 'Before Takeoff',
    phase: 'before takeoff',
    items: [
      { challenge: 'Parking Brake', response: 'SET', check: on(C172.parkingBrake) },
      { challenge: 'Pilot and Passenger Seat Backs', response: 'MOST UPRIGHT POSITION' },
      { challenge: 'Seats and Seat Belts', response: 'CHECK SECURE' },
      { challenge: 'Cabin Doors', response: 'CLOSED and LOCKED', check: (v) => v.get(C172.doorLeft) >= 2 && v.get(C172.doorRight) >= 2 },
      { challenge: 'Flight Controls', response: 'FREE and CORRECT', check: off(C172.controlLock) },
      { challenge: 'Flight Instruments (PFD)', response: "CHECK (no red X's)", check: (v) => v.get('adc1.valid') > 0.5 && v.get('ahrs1.valid') > 0.5 },
      { challenge: 'Altimeters: PFD (BARO), Standby Altimeter', response: 'SET' },
      { challenge: 'ALT SEL', response: 'SET' },
      { challenge: 'Standby Flight Instruments', response: 'CHECK', check: (v) => v.get('ac.vac.suction_inhg') >= 4.5 },
      { challenge: 'Fuel Quantity', response: 'CHECK (verify level is correct)' },
      { challenge: 'Mixture Control', response: 'RICH', check: mixtureRich },
      { challenge: 'FUEL SELECTOR Valve', response: 'SET BOTH', check: eq(C172.fuelSelector, FUEL_SEL.both) },
      { challenge: 'Autopilot', response: 'ENGAGE (push AP button on either PFD or MFD bezel)' },
      { challenge: 'Flight Controls', response: 'CHECK (verify autopilot can be overpowered in both pitch and roll axes)' },
      { challenge: 'A/P TRIM DISC Button', response: 'PRESS (verify autopilot disengages and aural alert is heard)', check: off('ap.engaged') },
      { challenge: 'Flight Director', response: 'OFF (push FD button on either PFD or MFD bezel)', check: off('ap.fd1_on') },
      { challenge: 'Elevator Trim Control', response: 'SET FOR TAKEOFF', check: (v) => Math.abs(v.get(C172.trimPosition) - 0.1) < 0.12 },
      { challenge: 'Throttle Control', response: '1800 RPM', check: (v) => Math.abs(v.get(ENG.rpm(1)) - 1800) < 60 },
      { challenge: '  MAGNETOS Switch', response: 'CHECK (drop ≤ 150 RPM each, ≤ 50 RPM differential)' },
      { challenge: '  VAC Indicator', response: 'CHECK', check: (v) => v.get('ac.vac.suction_inhg') >= 4.5 && v.get('ac.vac.suction_inhg') <= 5.5 },
      { challenge: '  Engine Indicators', response: 'CHECK' },
      { challenge: '  Ammeters and Voltmeters', response: 'CHECK' },
      { challenge: 'Annunciators', response: 'CHECK (verify no annunciators are shown)', check: (v) => v.get(ANN.lowVolts) < 0.5 && v.get(ANN.oilPress) < 0.5 && v.get(ANN.lowVacuum) < 0.5 && v.get(ANN.stbyBatt) < 0.5 },
      { challenge: 'Throttle Control', response: 'CHECK IDLE' },
      { challenge: 'Throttle Control', response: '1000 RPM or LESS', check: (v) => v.get(ENG.rpm(1)) <= 1050 },
      { challenge: 'Throttle Control Friction Lock', response: 'ADJUST' },
      { challenge: 'COM Frequency(s)', response: 'SET' },
      { challenge: 'NAV Frequency(s)', response: 'SET' },
      { challenge: 'FMS/GPS Flight Plan', response: 'AS DESIRED (check GPS availability on AUX-GPS STATUS page)' },
      { challenge: 'XPDR', response: 'SET' },
      { challenge: 'CDI Softkey', response: 'SELECT NAV SOURCE' },
      { challenge: 'CABIN PWR 12V Switch', response: 'OFF', check: off(C172.cabinPwr12v) },
      { challenge: 'Wing Flaps', response: 'UP - 10° (10° preferred)', check: flaps(0, 10) },
      { challenge: 'Cabin Windows', response: 'CLOSED and LOCKED', check: (v) => v.get(C172.windowLeft) < 0.05 && v.get(C172.windowRight) < 0.05 },
      { challenge: 'STROBE Light Switch', response: 'ON', check: on(C172.strobe) },
      { challenge: 'Brakes', response: 'RELEASE', check: off(C172.parkingBrake) },
    ],
  },
  {
    title: 'Normal Takeoff',
    phase: 'takeoff',
    items: [
      { challenge: 'Wing Flaps', response: 'UP - 10° (10° preferred)', check: flaps(0, 10) },
      { challenge: 'Throttle Control', response: 'FULL (push full in)', check: (v) => v.get(C172.throttle) > 0.97 },
      { challenge: 'Mixture Control', response: 'RICH (above 3000 ft pressure altitude, lean for maximum RPM)', check: mixtureRich },
      { challenge: 'Elevator Control', response: 'LIFT NOSEWHEEL AT 55 KIAS' },
      { challenge: 'Climb Airspeed', response: '70 - 80 KIAS' },
      { challenge: 'Wing Flaps', response: 'RETRACT (at safe altitude)', check: flaps(0, 0) },
    ],
  },
  {
    title: 'Short Field Takeoff',
    phase: 'takeoff',
    items: [
      { challenge: 'Wing Flaps', response: '10°', check: flaps(10, 10) },
      { challenge: 'Brakes', response: 'APPLY' },
      { challenge: 'Throttle Control', response: 'FULL (push full in)', check: (v) => v.get(C172.throttle) > 0.97 },
      { challenge: 'Mixture Control', response: 'RICH (above 3000 ft pressure altitude, lean for maximum RPM)' },
      { challenge: 'Brakes', response: 'RELEASE' },
      { challenge: 'Elevator Control', response: 'SLIGHTLY TAIL LOW' },
      { challenge: 'Climb Airspeed', response: '56 KIAS (until all obstacles are cleared)' },
      { challenge: 'Wing Flaps', response: 'RETRACT SLOWLY (when airspeed is more than 60 KIAS)' },
    ],
  },
  {
    title: 'Enroute Climb',
    phase: 'climb',
    items: [
      { challenge: 'Airspeed', response: '70 - 85 KIAS' },
      { challenge: 'Throttle Control', response: 'FULL (push full in)', check: (v) => v.get(C172.throttle) > 0.97 },
      { challenge: 'Mixture Control', response: 'RICH (above 3000 ft pressure altitude, lean for maximum RPM)' },
    ],
  },
  {
    title: 'Cruise',
    phase: 'cruise',
    items: [
      { challenge: 'Power', response: '2100 - 2700 RPM (no more than 75% power recommended)', check: (v) => v.get(ENG.rpm(1)) >= 2100 && v.get(ENG.rpm(1)) <= 2700 },
      { challenge: 'Elevator Trim Control', response: 'ADJUST' },
      { challenge: 'Mixture Control', response: 'LEAN (for desired performance or economy)' },
      { challenge: 'FMS/GPS', response: 'REVIEW and BRIEF (OBS/SUSP softkey operation for holding pattern procedure (IFR))' },
    ],
  },
  {
    title: 'Descent',
    phase: 'descent',
    items: [
      { challenge: 'Power', response: 'AS DESIRED' },
      { challenge: 'Mixture', response: 'ADJUST (if necessary to make engine run smoothly)' },
      { challenge: 'Altimeters: PFD (BARO), Standby Altimeter', response: 'SET' },
      { challenge: 'ALT SEL', response: 'SET' },
      { challenge: 'CDI Softkey', response: 'SELECT NAV SOURCE' },
      { challenge: 'FMS/GPS', response: 'REVIEW and BRIEF' },
      { challenge: 'FUEL SELECTOR Valve', response: 'BOTH', check: eq(C172.fuelSelector, FUEL_SEL.both) },
      { challenge: 'Wing Flaps', response: 'AS DESIRED (UP - 10° below 110 KIAS; 10° - FULL below 85 KIAS)' },
    ],
  },
  {
    title: 'Before Landing',
    phase: 'approach',
    items: [
      { challenge: 'Pilot and Passenger Seat Backs', response: 'MOST UPRIGHT POSITION' },
      { challenge: 'Seats and Seat Belts', response: 'SECURED and LOCKED' },
      { challenge: 'FUEL SELECTOR Valve', response: 'BOTH', check: eq(C172.fuelSelector, FUEL_SEL.both) },
      { challenge: 'Mixture Control', response: 'RICH', check: (v) => v.get(C172.mixture) > 0.8 },
      { challenge: 'LAND and TAXI Light Switches', response: 'ON', check: (v) => v.get(C172.land) > 0.5 && v.get(C172.taxi) > 0.5 },
      { challenge: 'Autopilot', response: 'OFF', check: off('ap.engaged') },
      { challenge: 'CABIN PWR 12V Switch', response: 'OFF', check: off(C172.cabinPwr12v) },
    ],
  },
  {
    title: 'Normal Landing',
    phase: 'landing',
    items: [
      { challenge: 'Airspeed', response: '65 - 75 KIAS (Flaps UP)' },
      { challenge: 'Wing Flaps', response: 'AS DESIRED (UP - 10° below 110 KIAS; 10° - FULL below 85 KIAS)' },
      { challenge: 'Airspeed', response: '60 - 70 KIAS (Flaps FULL)' },
      { challenge: 'Elevator Trim Control', response: 'ADJUST' },
      { challenge: 'Touchdown', response: 'MAIN WHEELS FIRST' },
      { challenge: 'Landing Roll', response: 'LOWER NOSEWHEEL GENTLY' },
      { challenge: 'Braking', response: 'MINIMUM REQUIRED' },
    ],
  },
  {
    title: 'Short Field Landing',
    phase: 'landing',
    items: [
      { challenge: 'Airspeed', response: '65 - 75 KIAS (Flaps UP)' },
      { challenge: 'Wing Flaps', response: 'FULL', check: flaps(30, 30) },
      { challenge: 'Airspeed', response: '61 KIAS (until flare)' },
      { challenge: 'Elevator Trim Control', response: 'ADJUST' },
      { challenge: 'Power', response: 'REDUCE TO IDLE (as obstacle is cleared)' },
      { challenge: 'Touchdown', response: 'MAIN WHEELS FIRST' },
      { challenge: 'Brakes', response: 'APPLY HEAVILY' },
      { challenge: 'Wing Flaps', response: 'UP', check: flaps(0, 0) },
    ],
  },
  {
    title: 'Balked Landing',
    phase: 'landing',
    items: [
      { challenge: 'Throttle Control', response: 'FULL (push full in)', check: (v) => v.get(C172.throttle) > 0.97 },
      { challenge: 'Wing Flaps', response: 'RETRACT to 20°' },
      { challenge: 'Climb Speed', response: '60 KIAS' },
      { challenge: 'Wing Flaps', response: '10° (as obstacle is cleared), then UP (after reaching a safe altitude and 65 KIAS)' },
    ],
  },
  {
    title: 'After Landing',
    phase: 'after landing',
    items: [{ challenge: 'Wing Flaps', response: 'UP', check: flaps(0, 0) }],
  },
  {
    title: 'Securing Airplane',
    phase: 'shutdown',
    items: [
      { challenge: 'Parking Brake', response: 'SET', check: on(C172.parkingBrake) },
      { challenge: 'Throttle Control', response: 'IDLE (pull full out)', check: throttleIdle },
      { challenge: 'Electrical Equipment', response: 'OFF' },
      { challenge: AVIONICS, response: 'OFF', check: avionicsOff },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'MAGNETOS Switch', response: 'OFF', check: eq(C172.magneto, MAG.off) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: 'Control Lock', response: 'INSTALL', check: on(C172.controlLock) },
      { challenge: 'FUEL SELECTOR Valve', response: 'LEFT or RIGHT (to prevent crossfeeding between tanks)', check: (v) => Math.round(v.get(C172.fuelSelector)) !== FUEL_SEL.both },
    ],
  },

  // ======================================================================= EMERGENCY (POH Section 3)
  {
    title: 'EMERGENCY — Engine Failure During Takeoff Roll',
    phase: 'emergency',
    items: [
      { challenge: 'Throttle Control', response: 'IDLE (pull full out)', check: throttleIdle },
      { challenge: 'Brakes', response: 'APPLY' },
      { challenge: 'Wing Flaps', response: 'RETRACT', check: flaps(0, 0) },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'MAGNETOS Switch', response: 'OFF', check: eq(C172.magneto, MAG.off) },
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
    ],
  },
  {
    title: 'EMERGENCY — Engine Failure Immediately After Takeoff',
    phase: 'emergency',
    items: [
      { challenge: 'Airspeed', response: '70 KIAS - Flaps UP; 65 KIAS - Flaps 10° - FULL' },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'FUEL SHUTOFF Valve', response: 'OFF (pull full out)', check: off(C172.fuelShutoff) },
      { challenge: 'MAGNETOS Switch', response: 'OFF', check: eq(C172.magneto, MAG.off) },
      { challenge: 'Wing Flaps', response: 'AS REQUIRED (FULL recommended)' },
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: 'Cabin Door', response: 'UNLATCH' },
      { challenge: 'Land', response: 'STRAIGHT AHEAD' },
    ],
  },
  {
    title: 'EMERGENCY — Engine Failure During Flight (Restart Procedures)',
    phase: 'emergency',
    items: [
      { challenge: 'Airspeed', response: '68 KIAS (best glide speed)' },
      { challenge: 'FUEL SHUTOFF Valve', response: 'ON (push full in)', check: on(C172.fuelShutoff) },
      { challenge: 'FUEL SELECTOR Valve', response: 'BOTH', check: eq(C172.fuelSelector, FUEL_SEL.both) },
      { challenge: 'FUEL PUMP Switch', response: 'ON', check: on(C172.fuelPump) },
      { challenge: 'Mixture Control', response: 'RICH (if restart has not occurred)' },
      { challenge: 'MAGNETOS Switch', response: 'BOTH (or START if propeller is stopped)' },
      { challenge: 'FUEL PUMP Switch', response: 'OFF (ON again if FFLOW GPH immediately drops to zero: engine-driven fuel pump failure)' },
    ],
  },
  {
    title: 'EMERGENCY — Emergency Landing Without Engine Power',
    phase: 'emergency',
    items: [
      { challenge: 'Pilot and Passenger Seat Backs', response: 'MOST UPRIGHT POSITION' },
      { challenge: 'Seats and Seat Belts', response: 'SECURE' },
      { challenge: 'Airspeed', response: '70 KIAS - Flaps UP; 65 KIAS - Flaps 10° - FULL' },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'FUEL SHUTOFF Valve', response: 'OFF (pull full out)', check: off(C172.fuelShutoff) },
      { challenge: 'MAGNETOS Switch', response: 'OFF', check: eq(C172.magneto, MAG.off) },
      { challenge: 'Wing Flaps', response: 'AS REQUIRED (FULL recommended)' },
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: MASTER, response: 'OFF (when landing is assured)' },
      { challenge: 'Doors', response: 'UNLATCH PRIOR TO TOUCHDOWN' },
      { challenge: 'Touchdown', response: 'SLIGHTLY TAIL LOW' },
      { challenge: 'Brakes', response: 'APPLY HEAVILY' },
    ],
  },
  {
    title: 'EMERGENCY — Precautionary Landing With Engine Power',
    phase: 'emergency',
    items: [
      { challenge: 'Seat Backs; Seats and Seat Belts', response: 'MOST UPRIGHT; SECURE' },
      { challenge: 'Airspeed', response: '65 KIAS' },
      { challenge: 'Wing Flaps', response: '20°' },
      { challenge: 'Selected Field', response: 'FLY OVER (noting terrain and obstructions)' },
      { challenge: 'Wing Flaps', response: 'FULL (on final approach)' },
      { challenge: 'Airspeed', response: '65 KIAS' },
      { challenge: STBY, response: 'OFF' },
      { challenge: MASTER, response: 'OFF (when landing assured)' },
      { challenge: 'Doors', response: 'UNLATCH PRIOR TO TOUCHDOWN' },
      { challenge: 'Touchdown', response: 'SLIGHTLY TAIL LOW' },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)' },
      { challenge: 'MAGNETOS Switch', response: 'OFF' },
      { challenge: 'Brakes', response: 'APPLY HEAVILY' },
    ],
  },
  {
    title: 'EMERGENCY — Fire During Start on Ground',
    phase: 'emergency',
    items: [
      { challenge: 'MAGNETOS Switch', response: 'START (continue cranking to start the engine)' },
      { challenge: 'If engine starts: Power', response: '1800 RPM for a few minutes, then SHUTDOWN and inspect' },
      { challenge: 'If engine fails to start: Throttle Control', response: 'FULL (push full in)' },
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'MAGNETOS Switch', response: 'START (continue cranking)' },
      { challenge: 'FUEL SHUTOFF Valve', response: 'OFF (pull full out)', check: off(C172.fuelShutoff) },
      { challenge: 'FUEL PUMP Switch', response: 'OFF', check: off(C172.fuelPump) },
      { challenge: 'MAGNETOS Switch', response: 'OFF', check: eq(C172.magneto, MAG.off) },
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: 'Engine', response: 'SECURE' },
      { challenge: 'Parking Brake', response: 'RELEASE', check: off(C172.parkingBrake) },
      { challenge: 'Fire Extinguisher; Airplane', response: 'OBTAIN; EVACUATE' },
      { challenge: 'Fire', response: 'EXTINGUISH' },
    ],
  },
  {
    title: 'EMERGENCY — Engine Fire in Flight',
    phase: 'emergency',
    items: [
      { challenge: 'Mixture Control', response: 'IDLE CUTOFF (pull full out)', check: mixtureCutoff },
      { challenge: 'FUEL SHUTOFF Valve', response: 'OFF (pull full out)', check: off(C172.fuelShutoff) },
      { challenge: 'FUEL PUMP Switch', response: 'OFF', check: off(C172.fuelPump) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: 'Cabin Vents', response: 'OPEN (as needed)' },
      { challenge: 'CABIN HT and CABIN AIR Control Knobs', response: 'OFF (push full in)', check: (v) => v.get(C172.cabinHeat) < 0.05 && v.get(C172.cabinAir) < 0.05 },
      { challenge: 'Airspeed', response: '100 KIAS (increase to find an incombustible mixture)' },
      { challenge: 'Forced Landing', response: 'EXECUTE' },
    ],
  },
  {
    title: 'EMERGENCY — Electrical Fire in Flight',
    phase: 'emergency',
    items: [
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: 'Cabin Vents', response: 'CLOSED (to avoid drafts)', check: (v) => v.get(C172.ventLeft) < 0.05 && v.get(C172.ventRight) < 0.05 },
      { challenge: 'CABIN HT and CABIN AIR Control Knobs', response: 'OFF (push full in)', check: (v) => v.get(C172.cabinHeat) < 0.05 && v.get(C172.cabinAir) < 0.05 },
      { challenge: 'Fire Extinguisher', response: 'ACTIVATE (if available)', check: on(C172.extinguisher) },
      { challenge: AVIONICS, response: 'OFF', check: avionicsOff },
      { challenge: 'All Other Switches (except MAGNETOS switch)', response: 'OFF' },
      { challenge: 'Cabin Vents; CABIN HT and CABIN AIR', response: 'OPEN / ON when sure the fire is completely extinguished' },
      { challenge: 'If power needed: Circuit Breakers', response: 'CHECK (for OPEN circuit(s), do not reset)' },
      { challenge: MASTER, response: 'ON' },
      { challenge: STBY, response: 'ARM' },
      { challenge: 'AVIONICS Switch (BUS 1), then (BUS 2)', response: 'ON' },
    ],
  },
  {
    title: 'EMERGENCY — Cabin Fire',
    phase: 'emergency',
    items: [
      { challenge: STBY, response: 'OFF', check: eq(C172.stbyBatt, STBY_BATT.off) },
      { challenge: MASTER, response: 'OFF', check: masterOff },
      { challenge: 'Cabin Vents', response: 'CLOSED (to avoid drafts)' },
      { challenge: 'CABIN HT and CABIN AIR Control Knobs', response: 'OFF (push full in)' },
      { challenge: 'Fire Extinguisher', response: 'ACTIVATE (if available)', check: on(C172.extinguisher) },
      { challenge: 'Cabin Vents; CABIN HT and CABIN AIR', response: 'OPEN / ON when sure the fire is completely extinguished' },
      { challenge: 'Land', response: 'AS SOON AS POSSIBLE to inspect for damage' },
    ],
  },
  {
    title: 'EMERGENCY — Wing Fire',
    phase: 'emergency',
    items: [
      { challenge: 'LAND and TAXI Light Switches', response: 'OFF', check: (v) => v.get(C172.land) < 0.5 && v.get(C172.taxi) < 0.5 },
      { challenge: 'NAV Light Switch', response: 'OFF', check: off(C172.nav) },
      { challenge: 'STROBE Light Switch', response: 'OFF', check: off(C172.strobe) },
      { challenge: 'PITOT HEAT Switch', response: 'OFF', check: off(C172.pitotHeat) },
      { challenge: 'Sideslip; Land', response: 'AS SOON AS POSSIBLE (flaps only as required)' },
    ],
  },
  {
    title: 'EMERGENCY — Inadvertent Icing Encounter',
    phase: 'emergency',
    items: [
      { challenge: 'PITOT HEAT Switch', response: 'ON', check: on(C172.pitotHeat) },
      { challenge: 'Course / Altitude', response: 'TURN BACK or CHANGE ALTITUDE' },
      { challenge: 'CABIN HT Control Knob', response: 'ON (pull full out)', check: (v) => v.get(C172.cabinHeat) > 0.9 },
      { challenge: 'Defroster Control Outlets', response: 'OPEN', check: (v) => v.get(C172.defrostLeft) > 0.9 && v.get(C172.defrostRight) > 0.9 },
      { challenge: 'CABIN AIR Control Knob', response: 'ADJUST (maximum defroster heat and airflow)' },
      { challenge: 'Throttle / Mixture', response: 'ADJUST to hold RPM (induction filter icing)' },
      { challenge: 'Landing', response: 'NEAREST AIRPORT; flaps retracted; approach 65-75 KIAS; level attitude' },
    ],
  },
  {
    title: 'EMERGENCY — Static Source Blockage',
    phase: 'emergency',
    items: [
      { challenge: 'ALT STATIC AIR Valve', response: 'ON (pull full out)', check: on(C172.altStatic) },
      { challenge: 'Cabin Vents', response: 'CLOSED' },
      { challenge: 'CABIN HT and CABIN AIR Control Knobs', response: 'ON (pull full out)', check: (v) => v.get(C172.cabinHeat) > 0.9 && v.get(C172.cabinAir) > 0.9 },
      { challenge: 'Airspeed', response: 'Refer to Section 5 Figure 5-1 (Sheet 2) alternate static source correction' },
    ],
  },
  {
    title: 'EMERGENCY — Excessive Fuel Vapor',
    phase: 'emergency',
    items: [
      { challenge: 'FUEL PUMP Switch', response: 'ON', check: on(C172.fuelPump) },
      { challenge: 'Mixture Control', response: 'ADJUST (as necessary for smooth engine operation)' },
      { challenge: 'FUEL SELECTOR Valve', response: 'SELECT OPPOSITE TANK (if vapor symptoms continue)' },
      { challenge: 'FUEL PUMP Switch', response: 'OFF (after fuel flow has stabilized)' },
    ],
  },
  {
    title: 'EMERGENCY — HIGH VOLTS Annunciator or M BATT AMPS More Than 40',
    phase: 'emergency',
    items: [
      { challenge: 'MASTER Switch (ALT Only)', response: 'OFF', check: off(C172.masterAlt) },
      { challenge: 'Electrical Load: AVIONICS (BUS 1), PITOT HEAT, BEACON, LAND, TAXI, NAV, STROBE, CABIN PWR 12V', response: 'OFF (reduce immediately)' },
      { challenge: 'COM1 and NAV1', response: 'TUNE TO ACTIVE FREQUENCY' },
      { challenge: 'COM1 MIC and NAV1', response: 'SELECT' },
      { challenge: 'AVIONICS Switch (BUS 2)', response: 'OFF (KEEP ON if in clouds)' },
      { challenge: 'Land', response: 'AS SOON AS PRACTICAL' },
    ],
  },
  {
    title: 'EMERGENCY — LOW VOLTS Annunciator Comes On',
    phase: 'emergency',
    items: [
      { challenge: 'Below 1000 RPM: Throttle Control', response: '1000 RPM; LOW VOLTS CHECK OFF' },
      { challenge: 'MASTER Switch (ALT Only)', response: 'OFF' },
      { challenge: 'ALT FIELD Circuit Breaker', response: 'CHECK IN', check: (v) => v.get('cb.alt_field', 1) > 0.5 },
      { challenge: MASTER, response: 'ON', check: masterOn },
      { challenge: 'LOW VOLTS Annunciator', response: 'CHECK OFF', check: off(ANN.lowVolts) },
      { challenge: 'M BUS VOLTS', response: 'CHECK 27.5 V (minimum)', check: (v) => v.get(C172.mBusV) >= 27.5 },
      { challenge: 'M BATT AMPS', response: 'CHECK CHARGING (+)', check: (v) => v.get(C172.mBattA) > 0 },
      { challenge: 'If LOW VOLTS remains on: MASTER (ALT Only) OFF, reduce load, COM1/NAV1 selected', response: 'LAND AS SOON AS PRACTICAL' },
    ],
  },
  {
    title: 'EMERGENCY — Air Data / AHRS Failure (Red X)',
    phase: 'emergency',
    items: [
      { challenge: 'ADC/AHRS Circuit Breakers (ESS BUS and AVN BUS 1)', response: 'CHECK IN (reset once; if it opens again, do not reset)', check: (v) => v.get('cb.adc_ahrs_ess', 1) > 0.5 && v.get('cb.adc_ahrs_avn1', 1) > 0.5 },
      { challenge: 'Standby Airspeed Indicator / Standby Altimeter', response: 'USE FOR AIRSPEED / ALTITUDE (altimeter setting CHECKED)' },
      { challenge: 'Standby Attitude Indicator', response: 'USE FOR ATTITUDE INFORMATION' },
      { challenge: 'Non-Stabilized Magnetic Compass', response: 'USE FOR HEADING INFORMATION' },
    ],
  },
  {
    title: 'EMERGENCY — Autopilot or Electric Trim Failure (AP or PTRM)',
    phase: 'emergency',
    items: [
      { challenge: 'Control Wheel', response: 'GRASP FIRMLY (regain control of airplane)' },
      { challenge: 'A/P TRIM DISC Button', response: 'PRESS and HOLD (throughout recovery)' },
      { challenge: 'Elevator Trim Control', response: 'ADJUST MANUALLY (as necessary)' },
      { challenge: 'AUTO PILOT Circuit Breaker', response: 'OPEN (pull out)', check: (v) => v.get('cb.autopilot', 1) < 0.5 },
      { challenge: 'A/P TRIM DISC Button', response: 'RELEASE', check: off('ac.c172g.ap_disc') },
    ],
  },
  {
    title: 'EMERGENCY — Display Cooling Advisory (PFD1 / MFD1 COOLING)',
    phase: 'emergency',
    items: [
      { challenge: 'CABIN HT Control Knob', response: 'REDUCE (push in) (minimum preferred)' },
      { challenge: 'Forward Avionics Fan', response: 'CHECK (feel for airflow from screen on glareshield)', check: on('ac.c172g.fwd_fan') },
      { challenge: 'If forward fan failed: STBY BATT Switch', response: 'OFF (unless needed for emergency power)' },
      { challenge: 'If advisory not off within 3 min or both come on: STBY BATT Switch', response: 'OFF (land as soon as practical)' },
    ],
  },
  {
    title: 'EMERGENCY — Vacuum System Failure (LOW VACUUM)',
    phase: 'emergency',
    items: [
      { challenge: 'Vacuum Indicator (VAC)', response: 'CHECK EIS ENGINE PAGE (pointer in green band)', check: (v) => v.get('ac.vac.suction_inhg') >= 4.5 },
      { challenge: 'Standby Attitude Indicator', response: 'DO NOT USE if VAC is out of the green band or the GYRO flag is shown' },
    ],
  },
  {
    title: 'EMERGENCY — High Carbon Monoxide (CO LVL HIGH)',
    phase: 'emergency',
    items: [
      { challenge: 'CABIN HT Control Knob', response: 'OFF (push full in)', check: (v) => v.get(C172.cabinHeat) < 0.05 },
      { challenge: 'CABIN AIR Control Knob', response: 'ON (pull full out)', check: (v) => v.get(C172.cabinAir) > 0.95 },
      { challenge: 'Cabin Vents', response: 'OPEN', check: (v) => v.get(C172.ventLeft) > 0.5 && v.get(C172.ventRight) > 0.5 },
      { challenge: 'Cabin Windows', response: 'OPEN (163 KIAS maximum windows open speed)' },
      { challenge: 'If CO LVL HIGH remains on', response: 'LAND AS SOON AS PRACTICAL' },
    ],
  },
];
