import { it } from 'vitest';
import { makeRig } from './helpers';
import { LON_VARS as V } from '../../../src/aircraft/citation-longitude/vars';
it('probe', { timeout: 300000 }, () => {
  const r = makeRig('cruise', { weightLb: 32000, avionics: true, air: { altFtMsl: 41000, iasKt: 230 } });
  const v = r.vars;
  r.run(2);
  console.log('ap before', v.get('ap.engaged'), v.getString('ap.lat_active'), v.get('elec.afcs_powered'), v.get('ahrs1.valid'), v.get('adc1.valid'));
  r.events.emit('g3k.gmc.key_ap');
  r.run(2);
  console.log('ap after', v.get('ap.engaged'), v.getString('ap.lat_active'), v.getString('ap.vert_active'));
  const a = makeRig('ready_to_taxi', { avionics: false });
  a.vars.set(V.apuKnob, 2);
  a.run(60, (t) => { if (Math.abs(t - 5) < 0.01 || Math.abs(t-30)<0.01) console.log('apu', t, a.vars.get('apu.n_pct'), a.vars.getString('apu.state'), a.vars.get('apu.starting')); });
  console.log('apu', a.vars.get('apu.avail'), a.vars.get('apu.n_pct'), a.vars.get('adc1.press_alt_ft'), a.vars.get('gear.air_ground'));
  const m = makeRig('cruise', { weightLb: 32000, avionics: true, air: { altFtMsl: 15000, iasKt: 200 } });
  m.run(1);
  m.vars.set(V.tla(1), 0); m.vars.set(V.tla(2), 0); m.vars.set(V.speedbrake, 1);
  m.run(60, (t) => { m.vars.set('input.pitch', 0.3); if (Math.round(t*60)%600===0) console.log('min', t, m.vars.get('adc1.ias_kt').toFixed(0), m.vars.get('stall.aoa_norm').toFixed(2), m.vars.get('fdm.pitch_deg').toFixed(1), m.vars.get('surf.elevator').toFixed(2), m.vars.get(V.atProt), m.vars.get('ra1.alt_ft')); });
});
