import { it } from 'vitest';
import { rig } from './helpers';
import { appendFileSync, writeFileSync } from 'node:fs';
const OUT = '/tmp/claude-0/-home-user-Smart-House/bac8bdb5-ed02-5dee-82cb-3c8efba4f51c/scratchpad/cdu.txt';
writeFileSync(OUT, '');

it('explore', async () => {
  const r = await rig();
  const show = (t: string) => appendFileSync(OUT, '\n' + `--- ${t}\n` + r.screen().map((l) => `|${l}|`).join('\n'));
  const wait = async () => {
    r.screen();
    await new Promise((res) => setTimeout(res, 60));
    r.step(0.1);
  };
  r.press('RTE');
  r.enter('KTEB', 'L1');
  r.enter('KBOS', 'R1');
  r.enter('24', 'L3');
  r.press('NEXT_PAGE');
  r.enter('DIXIE', 'R1');
  r.enter('V1', 'L2');
  r.enter('HFD', 'R2');
  r.enter('PUT', 'R3');
  r.enter('BOS', 'R4');
  show('rte2');
  r.press('PREV_PAGE', 'R6', 'EXEC');
  r.step(1);
  r.press('DEP_ARR', 'L1');
  await wait();
  show('departures');
  r.press('L1');
  await wait();
  show('dep sid sel');
  r.press('DEP_ARR', 'R2');
  await wait();
  show('arrivals');
  r.press('L3');
  await wait();
  show('star sel');
  r.press('R2');
  await wait();
  show('app sel');
  r.press('EXEC');
  r.step(1);
  r.press('LEGS');
  show('legs1');
  r.press('NEXT_PAGE');
  show('legs2');
  r.press('NEXT_PAGE');
  show('legs3');
  r.press('RTE', 'NEXT_PAGE');
  show('rte2 after procs');
  r.press('INIT_REF');
  r.enter('62.5', 'L3');
  r.enter('2.5', 'L4');
  r.enter('45', 'L5');
  r.enter('FL350', 'R1');
  r.step(0.5);
  show('perf init');
  r.press('EXEC');
  r.press('INIT_REF');
  show('init ref -> takeoff');
  r.enter('5', 'L1');
  r.enter('25', 'L3');
  r.step(0.5);
  show('takeoff flaps');
  r.press('R1', 'R2', 'R3');
  r.step(0.2);
  show('takeoff vspeeds');
  r.enter('26', 'L3');
  show('takeoff cg changed');
  r.press('CLR');
  r.press('NEXT_PAGE');
  show('takeoff 2');
  r.press('N1_LIMIT');
  r.enter('40', 'L1');
  r.press('L3');
  r.step(0.2);
  show('n1 derate');
  r.press('LEGS');
  show('legs with perf');
  r.press('CLB');
  show('clb');
  r.press('CRZ');
  show('crz');
  r.press('DES');
  show('des');
  r.press('CLR', 'CLR', 'CLR', 'CLR', 'CLR', 'CLR', 'CLR', 'CLR');
  r.press('FIX');
  r.enter('LGA', 'L1');
  r.enter('090', 'L2');
  r.enter('/20', 'L3');
  r.press('L5');
  show('fix');
  r.press('HOLD');
  r.enter('HFD', 'L6');
  show('hold page');
  r.enter('1.5', 'L4');
  r.enter('270/L', 'L3');
  show('hold edit');
  r.press('EXEC');
  r.press('INIT_REF', 'L6', 'L5');
  show('approach');
  r.press('R2');
  r.press('R4');
  show('approach vref');
  r.press('INIT_REF', 'L6', 'L2');
  show('pos init');
  r.press('NEXT_PAGE');
  show('pos ref');
  r.press('NEXT_PAGE');
  show('pos shift');
  r.press('PROG');
  show('prog');
  r.press('NEXT_PAGE', 'NEXT_PAGE');
  show('rnp prog');
  r.press('INIT_REF', 'L6', 'R1');
  r.enter('JFK', 'L1');
  show('nav data');
  // Take off and fly: airborne state, LNAV progress.
  r.vars.set('gear.air_ground', 0);
  r.vars.set('adc1.alt_ft', 16000);
  r.vars.set('adc1.tas_kt', 390);
  r.vars.set('adc1.ias_kt', 290);
  r.vars.set('ahrs1.hdg_true_deg', 60);
  r.vars.set('gps.gs_kt', 400);
  r.vars.set('gps.trk_true_deg', 55);
  r.vars.set('gps.lat_deg', 41.0);
  r.vars.set('gps.lon_deg', -73.55);
  r.step(3);
  r.press('LEGS');
  show('legs airborne');
  r.enter('HFD', 'L1');
  show('direct to HFD (MOD)');
  r.enter('070', 'R6');
  show('intc crs');
  r.press('EXEC');
  r.step(1);
  show('after exec direct');
  r.press('PROG');
  show('prog airborne');
  r.press('N1_LIMIT');
  show('n1 airborne');
  r.press('CRZ');
  show('crz airborne');
  r.press('HOLD');
  r.enter('PUT', 'L6');
  show('hold at PUT');
  r.press('EXEC');
  r.press('LEGS');
  show('legs with hold');
}, 60000);
