/**
 * Navigation database types. Data is generated by `scripts/build-navdata.mjs`
 * into `public/data/` and loaded by `nav/NavDatabase.ts`.
 *
 * Sources: OurAirports (public domain) for airports/runways/frequencies/navaids,
 * FlightGear/X-Plane nav.dat (GPL) for ILS/GS/DME/markers, fix.dat and awy.dat
 * for enroute fixes and airways, FAA CIFP (public domain, US) for procedures.
 */

export interface Runway {
  /** e.g. "09L" */
  ident: string;
  /** Opposite end ident, e.g. "27R". */
  oppositeIdent: string;
  lat: number;
  lon: number;
  /** Threshold elevation (ft MSL). */
  elevationFt: number;
  /** True heading of the runway centreline from this end. */
  headingTrue: number;
  lengthFt: number;
  widthFt: number;
  /** Displaced threshold distance (ft). */
  displacedFt: number;
  surface: 'asphalt' | 'concrete' | 'grass' | 'dirt' | 'gravel' | 'water' | 'snow' | 'unknown';
  lighted: boolean;
  /** ILS on this end, if any. */
  ils?: IlsInfo;
}

export interface IlsInfo {
  ident: string;
  freqMhz: number;
  /** Localizer course (true) and antenna position. */
  courseTrue: number;
  locLat: number;
  locLon: number;
  /** Glideslope, if present. */
  gsAngleDeg?: number;
  gsLat?: number;
  gsLon?: number;
  gsElevFt?: number;
  /** DME co-located, if present. */
  dmeLat?: number;
  dmeLon?: number;
  category?: string;
}

export interface Airport {
  icao: string;
  name: string;
  lat: number;
  lon: number;
  elevationFt: number;
  type: 'large_airport' | 'medium_airport' | 'small_airport' | 'heliport' | 'seaplane_base' | 'closed';
  country: string;
  municipality: string;
  /** Both ends of each physical runway appear (paired by oppositeIdent). */
  runways: Runway[];
  frequencies: { type: string; description: string; mhz: number }[];
  transitionAltitudeFt?: number;
}

export type NavaidType = 'VOR' | 'VORDME' | 'VORTAC' | 'TACAN' | 'DME' | 'NDB' | 'NDBDME' | 'LOC' | 'ILS' | 'GS' | 'OM' | 'MM' | 'IM';

export interface Navaid {
  ident: string;
  name: string;
  type: NavaidType;
  lat: number;
  lon: number;
  elevationFt: number;
  /** MHz for VHF navaids, kHz for NDBs. */
  freq: number;
  /** Nominal service range (nm). */
  rangeNm: number;
  /** Station declination / slaved variation (deg, + east) for VORs. */
  magVar: number;
  /** For LOC/ILS/GS: course true and GS angle. */
  courseTrue?: number;
  gsAngleDeg?: number;
  airport?: string;
  runway?: string;
}

export interface Fix {
  ident: string;
  lat: number;
  lon: number;
  region?: string;
}

export interface AirwaySegment {
  airway: string;
  from: string;
  to: string;
  high: boolean;
  minAltFt?: number;
}

export interface Waypoint {
  ident: string;
  lat: number;
  lon: number;
  kind: 'airport' | 'runway' | 'vor' | 'ndb' | 'fix' | 'user' | 'latlon';
}

export interface NavDatabase {
  readonly ready: boolean;
  load(): Promise<void>;
  airport(icao: string): Airport | undefined;
  airportsNear(lat: number, lon: number, radiusNm: number, limit?: number): Airport[];
  searchAirports(query: string, limit?: number): Airport[];
  navaidsByIdent(ident: string): Navaid[];
  navaidsNear(lat: number, lon: number, radiusNm: number, types?: NavaidType[]): Navaid[];
  /** VHF/NDB stations tuned on a frequency near a position (for radio receivers). */
  navaidsOnFreq(freq: number, lat: number, lon: number, radiusNm: number): Navaid[];
  fixesByIdent(ident: string): Fix[];
  fixesNear(lat: number, lon: number, radiusNm: number): Fix[];
  /** Resolve any ident (airport, navaid, fix) to candidates sorted by distance from a position. */
  resolve(ident: string, nearLat: number, nearLon: number): Waypoint[];
  airway(name: string): AirwaySegment[];
}
